spring.application.name=appointment-service

server.port=8084

# ============================================================================
# DATABASE (PostgreSQL)
# ============================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================================================
# FLYWAY (Database migrations)
# ============================================================================
spring.flyway.enabled=false

# ============================================================================
# EXTERNAL SERVICES
# ============================================================================
services.doctor.url=http://localhost:8082/doctors
services.patient.url=http://localhost:8083/patients
services.auth.url=http://localhost:5005/api/users

# ============================================================================
# LOGGING
# ============================================================================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.clinic.appointment_service=DEBUG

# ============================================================================
# ACTUATOR
# ============================================================================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# ============================================================================
# OPENAPI / SWAGGER UI
# ============================================================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# AWS Notification Settings
aws.sns.topic.appointment-booked=${AWS_SNS_APPOINTMENT_BOOKED}

# AWS EventBridge Scheduler
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.sqs.queue-arn=${AWS_SQS_QUEUE_ARN}
aws.eventbridge.role-arn=${AWS_EVENTBRIDGE_ROLE_ARN}
