import type { Notification } from './notification.types'

/**
 * Mock notification data covering all 5 notification types with a mix of read/unread states.
 * Used for stubbed API calls while backend endpoints are BLOCKED.
 */
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n-001-24h-reminder',
    type: 'APPOINTMENT_REMINDER_24H',
    title: 'Appointment Tomorrow',
    message: 'You have an appointment with Dr. Smith tomorrow at 09:00 AM.',
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-001',
      doctorId: 'doc-001',
      doctorName: 'Dr. Smith',
      slotDate: '2026-05-10',
      slotStart: '09:00:00',
      slotEnd: '09:30:00',
    },
  },
  {
    id: 'n-002-2h-reminder',
    type: 'APPOINTMENT_REMINDER_2H',
    title: 'Appointment in 2 Hours',
    message: 'Your appointment with Dr. Johnson is in 2 hours at 14:00.',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-002',
      doctorId: 'doc-002',
      doctorName: 'Dr. Johnson',
      slotDate: '2026-05-08',
      slotStart: '14:00:00',
      slotEnd: '14:30:00',
    },
  },
  {
    id: 'n-003-status-change',
    type: 'APPOINTMENT_STATUS_CHANGE',
    title: 'Appointment Status Updated',
    message: 'Your appointment status has been changed from BOOKED to ARRIVED.',
    isRead: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-003',
      previousStatus: 'BOOKED',
      newStatus: 'ARRIVED',
      doctorName: 'Dr. Williams',
    },
  },
  {
    id: 'n-004-prescription',
    type: 'PRESCRIPTION_READY',
    title: 'Prescription Ready',
    message: 'Your prescription from Dr. Brown is ready for pickup.',
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    metadata: {
      prescriptionId: 'rx-001',
      visitId: 'visit-001',
      doctorName: 'Dr. Brown',
    },
  },
  {
    id: 'n-005-cancelled',
    type: 'APPOINTMENT_CANCELLED',
    title: 'Appointment Cancelled',
    message: 'Your appointment with Dr. Davis on May 12 has been cancelled.',
    isRead: false,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-004',
      doctorName: 'Dr. Davis',
      slotDate: '2026-05-12',
      slotStart: '10:00:00',
      cancelledBy: 'doctor',
    },
  },
  {
    id: 'n-006-24h-read',
    type: 'APPOINTMENT_REMINDER_24H',
    title: 'Appointment Tomorrow',
    message: 'Reminder: You have an appointment with Dr. Martinez tomorrow at 11:00 AM.',
    isRead: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-005',
      doctorId: 'doc-005',
      doctorName: 'Dr. Martinez',
      slotDate: '2026-05-09',
      slotStart: '11:00:00',
      slotEnd: '11:30:00',
    },
  },
  {
    id: 'n-007-status-read',
    type: 'APPOINTMENT_STATUS_CHANGE',
    title: 'Visit Completed',
    message: 'Your visit with Dr. Wilson has been marked as COMPLETED.',
    isRead: true,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-006',
      previousStatus: 'IN_PROGRESS',
      newStatus: 'COMPLETED',
      doctorName: 'Dr. Wilson',
    },
  },
  {
    id: 'n-008-prescription-read',
    type: 'PRESCRIPTION_READY',
    title: 'Prescription Ready',
    message: 'Your prescription from Dr. Anderson is ready at the pharmacy.',
    isRead: true,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    metadata: {
      prescriptionId: 'rx-002',
      visitId: 'visit-002',
      doctorName: 'Dr. Anderson',
    },
  },
  {
    id: 'n-009-cancelled-read',
    type: 'APPOINTMENT_CANCELLED',
    title: 'Appointment Cancelled',
    message: 'The appointment with Dr. Taylor on May 5 was cancelled by the patient.',
    isRead: true,
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-007',
      doctorName: 'Dr. Taylor',
      slotDate: '2026-05-05',
      slotStart: '15:00:00',
      cancelledBy: 'patient',
    },
  },
  {
    id: 'n-010-2h-read',
    type: 'APPOINTMENT_REMINDER_2H',
    title: 'Appointment Soon',
    message: 'Your appointment with Dr. Thomas is starting in 2 hours.',
    isRead: true,
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-008',
      doctorId: 'doc-008',
      doctorName: 'Dr. Thomas',
      slotDate: '2026-05-03',
      slotStart: '16:00:00',
      slotEnd: '16:30:00',
    },
  },
  {
    id: 'n-011-status-unread',
    type: 'APPOINTMENT_STATUS_CHANGE',
    title: 'Appointment Confirmed',
    message: 'Dr. Lee has confirmed your appointment for May 15.',
    isRead: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    metadata: {
      appointmentId: 'apt-009',
      previousStatus: 'BOOKED',
      newStatus: 'CONFIRMED',
      doctorName: 'Dr. Lee',
    },
  },
  {
    id: 'n-012-prescription-unread',
    type: 'PRESCRIPTION_READY',
    title: 'New Prescription Available',
    message: 'Dr. Harris has issued a new prescription for your recent visit.',
    isRead: false,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    metadata: {
      prescriptionId: 'rx-003',
      visitId: 'visit-003',
      doctorName: 'Dr. Harris',
    },
  },
]
