spring.application.name=notification-service
server.port=8089

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Changed from update to create to handle the id column type change (String -> BigInt)
spring.jpa.hibernate.ddl-auto=create

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# AWS Configuration
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
spring.cloud.aws.region.static=${AWS_REGION}
aws.sqs.queue-name=${AWS_SQS_QUEUE_NAME}

# SQS Configuration
# Disable auto-creation globally and for the listener
spring.cloud.aws.sqs.queue-names-resolving-strategy=RESOLVE
spring.cloud.aws.sqs.listener.queue-names-resolving-strategy=RESOLVE
