spring.application.name=visit-service
server.port=8085

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.baseline-on-migrate=true


# External Services
services.patient.url=http://localhost:8083/patients
services.doctor.url=http://localhost:8082/doctors
services.appointment.url=http://localhost:8084/appointments
services.billing.url=http://localhost:8087/billing/invoices

# AWS S3 (Placeholders for now, or use localstack/mock if needed)
aws.s3.bucket-name=clinic-prescriptions
aws.region=us-east-1
aws.access-key=dummy
aws.secret-key=dummy

# Logging
logging.level.com.clinic.visit_service=DEBUG
