spring.application.name=billing-service
server.port=8087

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# External Services
services.patient.url=http://localhost:8083/patients
services.appointment.url=http://localhost:8084/appointments
services.visit.url=http://localhost:8085/visits

# Logging
logging.level.com.clinic.billing_service=DEBUG
